// skincare-app / app.js
// 本地存储键
const STORAGE_KEY = 'skincare_logs_v1';
function loadLogs(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return[];const arr=JSON.parse(raw);return Array.isArray(arr)?arr:[]}catch(e){console.error('loadLogs error',e);return[];}}
function saveLogs(logs){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(logs));}catch(e){console.error('saveLogs error',e);}}
function escapeHtml(str){return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function showToast(msg){const toast=document.getElementById('toast');if(!toast){alert(msg);return;}toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1600);}
const dateInput=document.getElementById('date');const amBtn=document.getElementById('amBtn');const pmBtn=document.getElementById('pmBtn');const productsInput=document.getElementById('products');const feelingInput=document.getElementById('feeling');const skinInput=document.getElementById('skin');const noteInput=document.getElementById('note');const saveBtn=document.getElementById('saveBtn');const statsSection=document.getElementById('stats');const productsSection=document.getElementById('products');const historySection=document.getElementById('history');const logSection=document.getElementById('logForm')||document.getElementById('log');const versionBadge=document.getElementById('version');if(versionBadge)versionBadge.textContent='v3.2.3';const tabButtons=document.querySelectorAll('#tabs .tab');let currentPeriod='AM';
function setPeriod(p){currentPeriod=p;if(amBtn&&pmBtn){if(p==='AM'){amBtn.classList.add('active');pmBtn.classList.remove('active');}else{pmBtn.classList.add('active');amBtn.classList.remove('active');}}}
if(amBtn&&pmBtn){amBtn.addEventListener('click',()=>setPeriod('AM'));pmBtn.addEventListener('click',()=>setPeriod('PM'));}
function initDate(){if(!dateInput)return;const d=new Date();const m=String(d.getMonth()+1).padStart(2,'0');const day=String(d.getDate()).padStart(2,'0');dateInput.value=`${d.getFullYear()}-${m}-${day}`;}
function handleSave(){if(!dateInput)return;const date=(dateInput.value||'').trim();if(!date){showToast('请先选择日期');return;}const products=(productsInput&&productsInput.value||'').trim();const feeling=(feelingInput&&feelingInput.value||'').trim();const skin=(skinInput&&skinInput.value||'').trim();const note=(noteInput&&noteInput.value||'').trim();const logs=loadLogs();const key=`${date}_${currentPeriod}`;const idx=logs.findIndex(l=>l.key===key);const item={key,date,period:currentPeriod,products,feeling,skin,note,ts:Date.now()};if(idx>=0)logs[idx]=item;else logs.push(item);saveLogs(logs);showToast('已保存');renderHistory();renderProducts();renderStats();}
if(saveBtn)saveBtn.addEventListener('click',handleSave);
function showTab(id){tabButtons.forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===id));if(logSection)logSection.classList.toggle('hide',id!=='log');if(statsSection)statsSection.classList.toggle('hide',id!=='stats');if(productsSection)productsSection.classList.toggle('hide',id!=='products');if(historySection)historySection.classList.toggle('hide',id!=='history');if(id==='stats')renderStats();if(id==='products')renderProducts();if(id==='history')renderHistory();try{localStorage.setItem('lastTab',id);}catch(e){}}
tabButtons.forEach(btn=>{btn.addEventListener('click',()=>showTab(btn.dataset.tab||'log'));});
function renderStats(){if(!statsSection)return;const logs=loadLogs().sort((a,b)=>b.ts-a.ts);const total=logs.length;if(!total){statsSection.innerHTML='<div class="card"><h3>统计</h3><p>暂无记录。</p></div>';return;}const latest=logs[0];const today=new Date();const d30=new Date(today.getTime()-29*24*60*60*1000);const days=new Set();logs.forEach(l=>{const d=new Date(l.date);if(!isNaN(d)&&d>=d30)days.add(l.date);});statsSection.innerHTML=`<div class="card"><h3>统计</h3><p>累计记录：<strong>${total}</strong></p><p>最近30天有记录：<strong>${days.size}</strong></p><p>最近一次：<strong>${latest.date} ${latest.period}</strong></p></div>`;}
function renderProducts(){if(!productsSection)return;const logs=loadLogs();const map=new Map();logs.forEach(l=>{const text=(l.products||'').trim();if(!text)return;text.split(/[,，；;、\s]/).map(s=>s.trim()).filter(Boolean).forEach(name=>{const item=map.get(name)||{name,count:0};item.count+=1;map.set(name,item);});});const list=Array.from(map.values()).sort((a,b)=>b.count-a.count);if(!list.length){productsSection.innerHTML='<div class="card"><h3>产品库</h3><p>暂无数据。</p></div>';return;}productsSection.innerHTML=`<div class="card"><h3>产品库</h3><ul>${list.map(p=>`<li>${escapeHtml(p.name)}（${p.count}次）</li>`).join('')}</ul></div>`;}
function renderHistory(){if(!historySection)return;const logs=loadLogs().sort((a,b)=>b.ts-a.ts);if(!logs.length){historySection.innerHTML='<div class="card"><h3>历史记录</h3><p>暂无记录。</p></div>';return;}historySection.innerHTML=`<div class="card"><h3>历史记录</h3><ul>${logs.map(l=>`<li><strong>${l.date} ${l.period}</strong><br>${l.products?'产品：'+escapeHtml(l.products)+'<br>':''}${l.feeling?'感受：'+escapeHtml(l.feeling)+'<br>':''}${l.skin?'皮肤：'+escapeHtml(l.skin)+'<br>':''}${l.note?'备注：'+escapeHtml(l.note):''}</li>`).join('')}</ul></div>`;}
(function init(){initDate();setPeriod('AM');let firstTab='log';try{const last=localStorage.getItem('lastTab');if(last)firstTab=last;}catch(e){}showTab(firstTab);renderStats();renderProducts();renderHistory();})();
if('serviceWorker'in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js').catch(e=>console.log('SW fail',e));});}
